# .github/workflows/run-tests.yml

name: Run Tests

on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to use v2
        with:
          submodules: recursive

      - name: Setup Node.js 20
        uses: actions/setup-node@v2  # Updated to use v2
        with:
          node-version: '20'

      - name: Setup Python 3.11
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
